name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make check script executable
        run: chmod +x ./check.sh

      - name: Run check script
        run: ./check.sh